# Generated by Django 3.2.7 on 2021-09-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='items',
        ),
    ]
