# Generated by Django 4.2.30 on 2026-05-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='merchants.merchantprofile'),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
